// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package webactions.proxies;

public enum PictureQuality
{
	original("1115598c-a748-44e8-91a3-2a3fab2f86a8"),
	low("60b52398-42dd-43dc-8178-4c863e3d11ba"),
	medium("2bae745e-4b65-469f-92ff-fa81c269ed80"),
	high("73c0fd31-56c2-4aa6-a1a1-094afc954bb4"),
	custom("71754a10-14df-4545-b0c0-591782b8da45");

	private final java.lang.String i18nCaptionKey;
	
	private PictureQuality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
