apiVersion: apps/v1
kind: Deployment
metadata:
  name: mendix-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mendix-app
  template:
    metadata:
      labels:
        app: mendix-app
    spec:
      containers:          
      - name: mendix-app
        image: nabilwics/med_app:1.0  
        ports:             
        - containerPort: 8080