// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Customer implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject customerMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Customer";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		bod("bod"),
		Gender("Gender"),
		Rhesus("Rhesus"),
		Customer_BloodGroup("MyFirstModule.Customer_BloodGroup");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Customer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Customer(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject customerMendixObject)
	{
		if (customerMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!customerMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.customerMendixObject = customerMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Customer initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Customer(context, mendixObject);
	}

	public static myfirstmodule.proxies.Customer load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Customer.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Customer> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.Customer.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of bod
	 */
	public final java.util.Date getbod()
	{
		return getbod(getContext());
	}

	/**
	 * @param context
	 * @return value of bod
	 */
	public final java.util.Date getbod(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.bod.toString());
	}

	/**
	 * Set value of bod
	 * @param bod
	 */
	public final void setbod(java.util.Date bod)
	{
		setbod(getContext(), bod);
	}

	/**
	 * Set value of bod
	 * @param context
	 * @param bod
	 */
	public final void setbod(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date bod)
	{
		getMendixObject().setValue(context, MemberNames.bod.toString(), bod);
	}

	/**
	 * @return value of Gender
	 */
	public final java.lang.String getGender()
	{
		return getGender(getContext());
	}

	/**
	 * @param context
	 * @return value of Gender
	 */
	public final java.lang.String getGender(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Gender.toString());
	}

	/**
	 * Set value of Gender
	 * @param gender
	 */
	public final void setGender(java.lang.String gender)
	{
		setGender(getContext(), gender);
	}

	/**
	 * Set value of Gender
	 * @param context
	 * @param gender
	 */
	public final void setGender(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String gender)
	{
		getMendixObject().setValue(context, MemberNames.Gender.toString(), gender);
	}

	/**
	 * @return value of Rhesus
	 */
	public final java.lang.String getRhesus()
	{
		return getRhesus(getContext());
	}

	/**
	 * @param context
	 * @return value of Rhesus
	 */
	public final java.lang.String getRhesus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Rhesus.toString());
	}

	/**
	 * Set value of Rhesus
	 * @param rhesus
	 */
	public final void setRhesus(java.lang.String rhesus)
	{
		setRhesus(getContext(), rhesus);
	}

	/**
	 * Set value of Rhesus
	 * @param context
	 * @param rhesus
	 */
	public final void setRhesus(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String rhesus)
	{
		getMendixObject().setValue(context, MemberNames.Rhesus.toString(), rhesus);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Customer_BloodGroup
	 */
	public final myfirstmodule.proxies.BloodGroup getCustomer_BloodGroup() throws com.mendix.core.CoreException
	{
		return getCustomer_BloodGroup(getContext());
	}

	/**
	 * @param context
	 * @return value of Customer_BloodGroup
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.BloodGroup getCustomer_BloodGroup(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.BloodGroup result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Customer_BloodGroup.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.BloodGroup.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Customer_BloodGroup
	 * @param customer_bloodgroup
	 */
	public final void setCustomer_BloodGroup(myfirstmodule.proxies.BloodGroup customer_bloodgroup)
	{
		setCustomer_BloodGroup(getContext(), customer_bloodgroup);
	}

	/**
	 * Set value of Customer_BloodGroup
	 * @param context
	 * @param customer_bloodgroup
	 */
	public final void setCustomer_BloodGroup(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.BloodGroup customer_bloodgroup)
	{
		if (customer_bloodgroup == null) {
			getMendixObject().setValue(context, MemberNames.Customer_BloodGroup.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Customer_BloodGroup.toString(), customer_bloodgroup.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return customerMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Customer that = (myfirstmodule.proxies.Customer) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
