// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Location implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject locationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Location";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		LocationName("LocationName"),
		Location_LocationLevel("MyFirstModule.Location_LocationLevel"),
		Location_Location("MyFirstModule.Location_Location");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Location(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Location(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject locationMendixObject)
	{
		if (locationMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!locationMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.locationMendixObject = locationMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Location initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Location(context, mendixObject);
	}

	public static myfirstmodule.proxies.Location load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Location.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Location> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.Location.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of LocationName
	 */
	public final java.lang.String getLocationName()
	{
		return getLocationName(getContext());
	}

	/**
	 * @param context
	 * @return value of LocationName
	 */
	public final java.lang.String getLocationName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LocationName.toString());
	}

	/**
	 * Set value of LocationName
	 * @param locationname
	 */
	public final void setLocationName(java.lang.String locationname)
	{
		setLocationName(getContext(), locationname);
	}

	/**
	 * Set value of LocationName
	 * @param context
	 * @param locationname
	 */
	public final void setLocationName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String locationname)
	{
		getMendixObject().setValue(context, MemberNames.LocationName.toString(), locationname);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Location_LocationLevel
	 */
	public final myfirstmodule.proxies.LocationLevel getLocation_LocationLevel() throws com.mendix.core.CoreException
	{
		return getLocation_LocationLevel(getContext());
	}

	/**
	 * @param context
	 * @return value of Location_LocationLevel
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.LocationLevel getLocation_LocationLevel(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.LocationLevel result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Location_LocationLevel.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.LocationLevel.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Location_LocationLevel
	 * @param location_locationlevel
	 */
	public final void setLocation_LocationLevel(myfirstmodule.proxies.LocationLevel location_locationlevel)
	{
		setLocation_LocationLevel(getContext(), location_locationlevel);
	}

	/**
	 * Set value of Location_LocationLevel
	 * @param context
	 * @param location_locationlevel
	 */
	public final void setLocation_LocationLevel(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.LocationLevel location_locationlevel)
	{
		if (location_locationlevel == null) {
			getMendixObject().setValue(context, MemberNames.Location_LocationLevel.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Location_LocationLevel.toString(), location_locationlevel.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Location_Location
	 */
	public final myfirstmodule.proxies.Location getLocation_Location() throws com.mendix.core.CoreException
	{
		return getLocation_Location(getContext());
	}

	/**
	 * @param context
	 * @return value of Location_Location
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Location getLocation_Location(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Location result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Location_Location.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Location.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Location_Location
	 * @param location_location
	 */
	public final void setLocation_Location(myfirstmodule.proxies.Location location_location)
	{
		setLocation_Location(getContext(), location_location);
	}

	/**
	 * Set value of Location_Location
	 * @param context
	 * @param location_location
	 */
	public final void setLocation_Location(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Location location_location)
	{
		if (location_location == null) {
			getMendixObject().setValue(context, MemberNames.Location_Location.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Location_Location.toString(), location_location.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return locationMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Location that = (myfirstmodule.proxies.Location) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
