// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package feedbackmodule.proxies;

public enum TranslationLanguages
{
	Dutch("0c3b14c0-96cd-4de9-891b-a39d1003f0a1"),
	English("2d4efc3f-9ef9-4744-98a7-87fdba25308b"),
	French("706a855b-9938-46bd-b9d5-a14d0d4f07a1"),
	German("507eab55-1173-4752-b95e-c7fcdd06625a"),
	Hindi("8785a22e-26cc-4453-9df1-6ce0f1edb164"),
	Portuguese("8aca1b4a-8504-42a8-8cc6-92b72529dd19"),
	Spanish("a57fff38-9ae1-4010-8925-9116a3d08613"),
	Turkish("85610d0e-115b-4f9e-94c5-b78895e38ddf");

	private final java.lang.String i18nCaptionKey;
	
	private TranslationLanguages(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
