// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("ebddab91-31b8-4774-b733-71daa21c20c0"),
	startsWith("40307fcd-e978-4c48-9bb4-778fb5a3f8a1"),
	endsWith("dcca3389-6ef2-465e-aa8e-21172412c0cd"),
	between("e6ec99ce-4af1-4d61-975c-f37b16acbfcc"),
	greater("6a88a269-cec3-4bc6-acc0-65fd606548d6"),
	greaterEqual("b779204f-15a7-4d3e-8566-67c340e32253"),
	equal("e37ffc02-13ec-48e1-8753-79a28b8218fe"),
	notEqual("3dad3d05-0a26-4968-ba25-74e70cde0fde"),
	smaller("257a2a4f-cf1d-41cb-b691-96dff9507714"),
	smallerEqual("c0eeda63-af29-4a6e-b21a-9f2824cc7739"),
	empty("cc29277d-af3f-4ef2-95a8-c819cbd70e18"),
	notEmpty("f64d627b-5959-42bc-b0b0-7687b5414761");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
